### DISCUSSION TITLE
How to run ChatGPT-Next-Web with docker compose?

### DISCUSSION THREAD

**Discussion by Screek1337** [ChatGPTNextWeb/NextChat#2921] [Q&A]
Hey guys!
How to run How to run ChatGPT-Next-Web with docker compose?
I've got docker-compose.yaml from this repo, set up .env file with all variables, but keep getting "no service selected" error after running docker compose up

**Comment by Wffv9FNa** [comment]
This is what I used in portainer:

```
version: '3'
services:
  chatgpt-next-web:
    image: yidadaa/chatgpt-next-web
    container_name: chatgpt-ui
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - OPENAI_API_KEY=xxxxxxxxx
      - CODE=xxxxxxxxx
```

Obviously replace with your own API KEY and desired password.
