### DISCUSSION TITLE
[Share] Configuration Kubernetes (k8s) for this repository

### DISCUSSION THREAD

**Discussion by H0llyW00dzZ** [ChatGPTNextWeb/NextChat#4100] [Ideas]
- Deployment:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatgptnextweb-app
  labels:
    app: chatgptnextweb-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chatgptnextweb-app
  template:
    metadata:
      labels:
        app: chatgptnextweb-app
    spec:
      containers:
      - name: chatgptnextweb
        image: <your-registry>/<your-image-name>:<tag>
        ports:
        - containerPort: 3000
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: api-keys
              key: openai
        - name: GOOGLE_API_KEY
          valueFrom:
            secretKeyRef:
              name: api-keys
              key: google
        - name: CODE
          value: ""
        - name: PROXY_URL
          value: ""
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: chatgptnextweb-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: chatgptnextweb-app-app
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 50
```

> [!NOTE]  
> This is just an example of a spec deployment for Kubernetes (k8s). You may also need to bind the cluster role. Below is the example

- Example bind cluster configuration:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ingress-nginx-leader-election-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ingress-nginx-leader-election-role
subjects:
- kind: ServiceAccount
  name: ingress-nginx
  namespace: ingress-nginx
```

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ingress-nginx
rules:
  - apiGroups: [""]
    resources: ["configmaps", "endpoints", "pods", "services", "events"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["extensions", "networking.k8s.io"]
    resources: ["ingresses", "ingressclasses", "ingresses/status"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["discovery.k8s.io"]
    resources: ["endpointslices"]
    verbs: ["get", "list", "watch"]
```

**Comment by H0llyW00dzZ** [comment]
# Additional Note
> [!NOTE]  
> `bind the cluster role` it's cheap unlike when using `load balancer`

**Comment by H0llyW00dzZ** [comment]
another configuration for binding cluster
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ingress-nginx
rules:
  - apiGroups: [""]
    resources: ["configmaps", "endpoints", "pods", "services", "events", "secrets"] # Adding Secrets for CertManager
    verbs: ["get", "list", "watch"]
  - apiGroups: ["extensions", "networking.k8s.io"]
    resources: ["ingresses", "ingressclasses", "ingresses/status"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["discovery.k8s.io"]
    resources: ["endpointslices"]
    verbs: ["get", "list", "watch"]
```
