### DISCUSSION TITLE
[Share] Configuration Kubernetes (k8s) for one-api

### DISCUSSION THREAD

**Discussion by H0llyW00dzZ** [ChatGPTNextWeb/NextChat#4114] [Ideas]
<div align="center">
  <img src="https://i.imgur.com/XdKlrSX.png" width="100">
<b>&</b>
  <img src="https://i.imgur.com/44oseJK.png" width="100">
</div>

---

**Introduction:**
I am sharing this Kubernetes (k8s) configuration for [`one-api`](https://github.com/songquanpeng/one-api) because it has proven to be stable when used with this repository.

- **The backend is written in Go and uses the Gin package**
> [!NOTE]  
> The backend, written in Go and using the Gin package, is a microservice architecture. Therefore, you don't need to create many pods for `one-api`. A single pod, along with `hpa`, is sufficient.

---

**Deployment:**

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: one-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: one-api
  template:
    metadata:
      labels:
        app: one-api
    spec:
      containers:
      - name: one-api
        image: ghcr.io/songquanpeng/one-api:v0.6.0-alpha.3 # Modify this as well
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        volumeMounts:
        - mountPath: "/data"
          name: data-volume
        env:
        - name: SESSION_SECRET
          value: yZlNPz2gciO8HqVCrhn0 # this just random string
        - name: SYNC_FREQUENCY
          value: "60"
        - name: CHANNEL_UPDATE_FREQUENCY
          value: "1440"
        - name: CHANNEL_TEST_FREQUENCY
          value: "1440"
        - name: POLLING_INTERVAL
          value: "5"
        - name: NODE_TYPE
          value: master
        - name: SQL_DSN
          valueFrom: # this important you need to use secrets, for example I am using mysql for this
            secretKeyRef:
              key: sql-dsn
              name: my-db-secret
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: one-api-storage

```

> [!NOTE]  
> For the deployment, even if you initially set `replica 3`, it will be automated adjusted to 1 after you set up the Horizontal Pod Autoscaler (HPA), as shown below.

**Horizontal Pod Autoscaler (HPA):**

```yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: one-api-hpa
  namespace: one-api-namespace # this namespace
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: one-api
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
```
**Storage:**

```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: one-api-storage
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /mnt/data
```
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: one-api-storage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "standard"
  resources:
    requests:
      storage: 5Gi
```
> [!NOTE]  
> This storage can be used for SQLite or any other storage needs you may have.

---

<div align="center">
  <img src="https://download.logo.wine/logo/Nginx/Nginx-Logo.wine.png" width="500">
</div>

> [!NOTE]  
> The configuration below is for nginx used with [`one-api`](https://github.com/songquanpeng/one-api). You won't need to configure it manually as you would with docker.

---

**Services:**
```yaml
apiVersion: v1
kind: Service
metadata:
  name: one-api-service
spec:
  selector:
    app: one-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
```

**Cluster Role:**
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ingress-nginx-leader-election-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ingress-nginx-leader-election-role
subjects:
- kind: ServiceAccount
  name: ingress-nginx
  namespace: ingress-nginx
```
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ingress-nginx
rules:
  - apiGroups: [""]
    resources: ["configmaps", "endpoints", "pods", "services", "events", "secrets"] # Adding Secrets for CertManager
    verbs: ["get", "list", "watch"]
  - apiGroups: ["extensions", "networking.k8s.io"]
    resources: ["ingresses", "ingressclasses", "ingresses/status"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["discovery.k8s.io"]
    resources: ["endpointslices"]
    verbs: ["get", "list", "watch"]
```

**Ingress Nginx**

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: one-api-ingress
  namespace: one-api-namespace
  annotations:
    kubernetes.io/ingress.class: "nginx" # This may vary depending on your Ingress controller
    cert-manager.io/cluster-issuer: "letsencrypt-prod" # Ensure this matches the name of your ClusterIssuer
spec:
  ingressClassName: nginx
  rules:
  - host: your-site.com # modify this
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: one-api-service
            port:
              number: 80
  tls: # Define the TLS section to enable HTTPS
  - hosts:
    - your-site.com # modify this
    secretName: your-site-com-tls # Cert-Manager will store the acquired certificate here
  ```
