### DISCUSSION TITLE
关于Nginx反代在二级目录下的配置咨询

### DISCUSSION THREAD

**Discussion by ixmu** [ChatGPTNextWeb/NextChat#4122] [General]
想把网络中的ChatGPT-Next-Web服务进行反代，实现：
访问http://www.baidu.com/chatgpt直接访问
也就是把目标地址http://localhost:3000放在chatgpt这个二级目录下
请问如何实现

**Comment by H0llyW00dzZ** [comment]
in k8s it's so easy

example:
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chatgptnextweb-ingress
  namespace: chatgptnextweb-namespace
  annotations:
    kubernetes.io/ingress.class: "nginx" # This may vary depending on your Ingress controller
    cert-manager.io/cluster-issuer: "letsencrypt-prod" # Ensure this matches the name of your ClusterIssuer
spec:
  ingressClassName: nginx
  rules:
  - host: your-site.com # modify this
    http:
      paths:
      - path: / # modify this for customize path
        pathType: Prefix
        backend:
          service:
            name: chatgptnextweb-service
            port:
              number: 80
  tls: # Define the TLS section to enable HTTPS
  - hosts:
    - your-site.com # modify this
    secretName: your-site-com-tls # Cert-Manager will store the acquired certificate here

 ```
