### ISSUE TITLE
[Bug] 文档里缺少mcp的使用说明

### ISSUE THREAD

**Issue by donghao1393** [ChatGPTNextWeb/NextChat#6114]
### 📦 部署方式

Docker

### 📌 软件版本

latest

### 💻 系统环境

macOS

### 📌 系统版本

14.7.2

### 🌐 浏览器

Other

### 📌 浏览器版本

Vivaldi 7.0.3495.29

### 🐛 问题描述

在本项目下面，我搜索不到mcp的配置说明，除了一句`ENABLE_MCP=true`，让人摸不着头脑。config.json怎么配置？

### 📷 复现步骤

docker compose up -d

### 🚦 期望结果

用户应该能配置和使用mcp服务，例如通过filesystem读取本地文件

**Comment by Leizhenpeng** [comment]
这是一个实验性的模块，还不稳定啊，就是后面稳定之后，我们会以文档的方式告诉大家怎么使用的。

**Comment by donghao1393** [comment]
我加了`ENABLE_MCP=true`进行镜像编译
然后使用了下面的`docker-compose.yaml`文件内容：
```yaml
services:
  chatgpt-next-web:
    container_name: chatgpt-next-web
    image: nextchat:250130
    ports:
      - 3000:3000
    environment:
      - ANTHROPIC_API_KEY=***
    volumes:
      - ./my_mcp_config.json:/app/app/mcp/mcp_config.json
```

启动以后
```bash
$ docker compose up -d
[+] Running 2/2
 ✔ Network nextchat_default    Created                                                                                                                                                                                                        0.1s
 ✔ Container chatgpt-next-web  Started
```

在网页对话框里，没有看到mcp相关的配置。
我就本地映射了一个配置好的`mcp_config.json`文件，然后在对话中请求它读取我的一个本地文件，AI说
> 我无法直接访问您计算机上的文件。如果您想让我帮您查看和分析该文件,请将文件内容复制并粘贴到我们的对话中。这样我就能看到文件内容并为您提供相关建议和分析。
