### ISSUE TITLE
[Feature Request] 希望修改docker image提交绑定事件

### ISSUE THREAD

**Issue by happyhappyhappy-arch** [ChatGPTNextWeb/NextChat#6147]
### 🥰 需求描述

代码更新频率远高于发布频率，而旧有的docker image build工作流由发布触发。
使用docker部署时没有办法快速获取更新，非常痛苦

### 🧐 解决方案

修改`.github/workflows/docker.yml`中的触发条件如下：
```
on:
  workflow_dispatch:
  push:
    branches:
      - master
```
