### ISSUE TITLE
[Bug] frp映射异常，如何卸载

### ISSUE THREAD

**Issue by fu9809** [ChatGPTNextWeb/NextChat#6169]
### 📦 部署方式

Docker

### 📌 软件版本

v2.15.8

### 💻 系统环境

Ubuntu

### 📌 系统版本

22.2

### 🌐 浏览器

Edge

### 📌 浏览器版本

最新版

### 🐛 问题描述

使用docker compose部署的next-chat；
```
version: '3'

services:
  next-chat:
    container_name: next-chat
    image: yidadaa/chatgpt-next-web:v2.15.8
    restart: always
    networks:
      - 1panel-network
    ports:
      - "127.0.0.1:3030:3000"
    environment:
      - TZ=Asia/Shanghai
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CODE=${CODE}
      - PROXY_URL=${PROXY_URL}

networks:
  1panel-network:
    external: true
```
本机是frp客户端，配置的是 
[[proxies]]
name = "chat"
type = "http"
localPort = 3030
customDomains = ["chat.pro.xxx.top"]
访问正常！

但是会影响frp的其他域名配置，所有的泛域名都会被映射到 这个 next-chat.  *.pro.xxx.top 都会去访问这个nextchat

更离谱的是，我把docker容器都已经删除了，并且重启了docker，它还是会访问 nextchat。

如何将这个东西彻底删除

### 🚦 期望结果

期望我的frp正常使用，不要再访问 next-chat 页面了
