### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by takidla** [ChatGPTNextWeb/NextChat#6197]
### 🥰 Feature Description

我部署的是docker镜像，目前最新的v2.15.8，用的是腾讯云提供的deepseek大模型R1，在使用时，我发现nextweb上不会显示think过程，而我直接调用腾讯云的api接口是有的。请问是目前版本还没针对腾讯云的deepseek做出think功能，还是我配置有问题呢？另外，我看到github上的图是有think功能的。

### 🧐 Proposed Solution

解决调用腾讯云的deepseek R1，没有think过程的问题

**Comment by crhywun** [comment]
请问腾讯接口怎么设置的啊

**Comment by zhaungmuwkeng** [comment]
请问腾讯接口怎么设置的啊

**Comment by takidla** [comment]
关于上面问到腾讯接口怎么设置的，我的docker compose设置如下：
version: '3.3'
services:
    chatgpt-next-web-latest:
        ports:
            - 3002:3002
        environment:
            - OPENAI_API_KEY=sk-123
            - BASE_URL=https://api.lkeap.cloud.tencent.com/
            - CODE=123    # 填一个密码，不然你的额度很快就会被刷完
            - CUSTOM_MODELS=-all,+deepseek-v3,+deepseek-r1
            - HOSTNAME=0.0.0.0
        image: yidadaa/chatgpt-next-web:latest
        network_mode: host
@crhywun @zhaungmuwkeng

**Comment by iAoe444** [comment]
打开控制台我发现思维链的内容存在websocket里面的ReasoningContent里面，应该修改一下代码就可以

**Comment by theores** [comment]
同样的问题，用阿里百炼deepseek是有的，但是需要用网友上传的Nightly版本镜像，因为官方镜像已经很久没有更新了。
```yaml
version: '3'

services:
  nextchat:
    image: rocky9/nextchat-nightly:latest
    container_name: nextchat
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DEEPSEEK_URL=https://dashscope.aliyuncs.com/compatible-mode/v1
      - DEEPSEEK_API_KEY=sk-xxx
      - CODE=xxx
      - CUSTOM_MODELS=+deepseek-r1@DeepSeek
      - DEFAULT_MODEL=deepseek-r1@DeepSeek
```
