### ISSUE TITLE
[Bug] 自定义模型分组无法使用，报错 you are not allowed to use xxx model

### ISSUE THREAD

**Issue by i-square** [ChatGPTNextWeb/NextChat#6242]
### 📦 Deployment Method

Docker

### 📌 Version

v2.16.0

### 💻 Operating System

Ubuntu

### 📌 System Version

22.04

### 🌐 Browser

Chrome

### 📌 Browser Version

latest

## 使用背景
我目前在使用 `v2.15.3`，`docker` 部署方式
各个渠道的key都使用 `one-api` 管理，然后在启动 `next-chat` 时设置
```bash
-e CUSTOM_MODELS="-all,+gpt-3.5-turbo@AZ-OAI,AZ/DeepSeek-R1@AZ-AI,gpt-4o@openai,claude-3-5-sonnet@BP-Anthropic,Qwen/Qwen2.5-7B-Instruct@硅基流动,THUDM/glm-4-9b-chat@硅基流动,glm-4-flash@智谱"
```
这个 `model_name@group_name` 的方式在UI展示上很好用

## 错误描述
用同样的 `CUSTOM_MODELS` 启动，最新的版本里UI显示没问题，但使用自定义模型时会报错：
```json
{
  "error": true,
  "message": "you are not allowed to use xxx model"
}
```
只有后面 `@openai`,`@OpenAI` 或者不加`@xxx` 的自定义模型可以用，但是这样定义的 `DeepSeek-R1` 模型无法展示思考过程

## 预期
希望能够继续使用 `model_name@group_name` 的方式来展示和使用

**Comment by zhaojie199512** [comment]
我也是这个问题，去掉@后就可以使用

**Comment by Kosette** [comment]
modelname@provider格式中后面的provider是指定服务商的，不是用来随便指定分组打标签的。

目前只有内置支持的服务商可以选择，比如OpenAI，Anthropic，Deepseek等等，你使用one-api中转，按照OpenAI的格式转发，那自定义模型只能选择@OpenAI，或者按照默认值不写。

**Comment by ccwav** [comment]
既然@openai算是渠道方式选择，能否提供另一种方式作为模型分组标识？

**Comment by QAbot-zh** [comment]
本来是可以的，但是修复这个 bug 的 pr 被搁置了

**Comment by QAbot-zh** [comment]
如果是展示需要，可以通过 displayName

**Comment by i-square** [comment]
> modelname@provider格式中后面的provider是指定服务商的，不是用来随便指定分组打标签的。
> 
> 目前只有内置支持的服务商可以选择，比如OpenAI，Anthropic，Deepseek等等，你使用one-api中转，按照OpenAI的格式转发，那自定义模型只能选择`@OpenAI`，或者按照默认值不写。

也就是说之前版本能够使用这个方式打标签才是bug？😂

**Comment by i-square** [comment]
> 本来是可以的，但是修复这个 bug 的 pr 被搁置了

#6000 看到了，还是希望能支持自定义打标签功能，比较方便。displayName只是修改了模型名，后面括号里的provider没变，没起到分类的目的

**Comment by downdawn** [comment]
这个还是不行吗？

配置：
```
services:
  chatgpt-next-web:
    image: yidadaa/chatgpt-next-web:v2.16.0
    container_name: chatgpt-next-web
    ports:
      - "3000:3000"
    restart: always
    environment:
      OPENAI_API_KEY: sk-xxx-xxx
      PROXY_URL: xxx
      DEFAULT_MODEL: gpt-4o
      BYTEDANCE_URL: https://ark.cn-beijing.volces.com/api/v3
      BYTEDANCE_API_KEY: xxx-xxx
      CUSTOM_MODELS: +deepseek-v3-241226@bytedance=deepseek-v3-241226
```

无法用，出现异常

![Image](https://github.com/user-attachments/assets/958c202e-fb42-4a9a-a289-46e3e3789bb2)
