### ISSUE TITLE
[Bug] MCP execution failed

### ISSUE THREAD

**Issue by redscholar** [ChatGPTNextWeb/NextChat#6437]
### 📦 部署方式

Other, Docker

### 📌 软件版本

docker.io/yidadaa/chatgpt-next-web:v2.16.0

### 💻 系统环境

Other, Ubuntu

### 📌 系统版本

kubernetes v1.23.15

### 🌐 浏览器

Safari

### 📌 浏览器版本

none

### 🐛 问题描述

1. 在kubernetes中部署NextChat和自定义的mcp-server
这个是我的环境变量配置：
```yaml
            - name: BASE_URL
              value: 'https://openapi.coreshub.cn'
            - name: OPENAI_API_KEY
              value: xxxx
            - name: ENABLE_MCP
              value: 'true'
            - name: CUSTOM_MODELS
              value: '-all,DeepSeek-V3,DeepSeek-R1'
            - name: DEFAULT_MODEL
              value: DeepSeek-V3
```
这是我的mcp_config配置：
```json
{
  "mcpServers": {
    "kubesphere": {
      "args": [
        "-y",
        "mcp-remote",
        "http://ks-mcp-server.kubesphere-system.svc/sse",
        "--clean"
      ],
      "command": "npx"
    }
  }
}
```
2. 页面发起请求后。报错MCP execution failed
![Image](https://github.com/user-attachments/assets/bb82eefd-77c6-4bf3-b78c-60caece1bc3b)
**从页面输出来看，已经获取到了我自定义的mcp-server的tool list**
这个是报错日志：
![Image](https://github.com/user-attachments/assets/1f860982-4c54-4b98-97b8-ea3d4a6bc566)
有一点我很困惑，我的mcp-server里面只配置了kubesphere。但是日志里面报错的是kubernetes的mcp-client找不到。
